[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy: default-src 'none'; 
                         script-src 'self' https://unpkg.com/leaflet 'unsafe-inline'; 
                         style-src 'self' https://unpkg.com/leaflet 'unsafe-inline'; 
                         img-src *;
                         font-src 'self'; 
                         connect-src 'self' https://commons.wikimedia.org; 
                         frame-ancestors 'none'; 
                         media-src 'self'